templates/NewsAndEventsの作成
shimamaru/shimamaru-frontend-basic-last-assignment pull request #12
Opened 2022-11-30 04:07 UTC by shimamaru

## セルフチェック
- [x] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [x] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [x] 記述の重複はないか

2022-12-01 15:34 UTC, caramelribon reviewed
コメントしました！

2022-12-01 15:34 UTC, caramelribon commented on src/components/templates/NewsAndEvents.scss
> +  padding: 60px 14% 57px;
ここのpaddingがfigmaの値と異なっているので、もう一度見直してみてください！

2022-12-01 15:34 UTC, caramelribon commented on src/components/templates/NewsAndEvents.scss
> +
画面サイズmd以下のときにnewsに`margin`がついているので修正お願いします！！

2022-12-02 04:07 UTC, shimamaru commented on src/components/templates/NewsAndEvents.scss
> +  padding: 60px 14% 57px;
<img width="431" alt="スクリーンショット 2022-12-02 12 29 03" src="https://user-images.githubusercontent.com/115210019/205212170-e8541e0d-8e32-4108-a001-d6ede1c94ef3.png">

<img width="547" alt="スクリーンショット 2022-12-02 13 00 53" src="https://user-images.githubusercontent.com/115210019/205212196-f1707bb5-e2af-42b7-9fce-d658105c27f1.png">

いつもコメントありがとうございます！
質問失礼します。
上記のようにカンプのpx通りにコーディングするとsp版で見たときに大きくレイアウトが崩れてしまい、使用しずらい感じになってしまうので、％指定で画面幅が変わってもユーザーが見やすいようにしています。
こういった場合はどうすればいいのでしょうか？

一般的に上下の空白はpaddingで設定すればmarginによる相殺もなくうまくいくというのはわかるのですが、横方向の空白の作成方法についてはいまだにはっきりとわかりません。自分の中では％を計算して実装するのが一番使いやすいかと思います。
ご意見をよろしくお願いします！

2022-12-02 04:10 UTC, shimamaru commented on src/components/templates/NewsAndEvents.scss
> +
marginでは相殺が起こる場合があるのでpaddingで設定してほしい、との要望をいただいたことがあるのでpaddingで設定しました。

2022-12-02 12:54 UTC, caramelribon commented on src/components/templates/NewsAndEvents.scss
> +  padding: 60px 14% 57px;
ご質問ありがとうございます！！
このfigmaのデザインがこのような余白になっている意図は、bootstrapのcontainerをつかうことを想定しているためです！containerについては以下のお役立ち資料を参考にしてください！
参考資料https://playground.wraptas.site/df6859770f3c4c248688d88eadad03cf

修正するには以下の2点のどちらかになると思います！
1. bootstrapのcontainerを使用する

2. figmaのこの部分のpaddingの値を使用する
![スクリーンショット (998)](https://user-images.githubusercontent.com/91133956/205296800-540b53ad-1bda-41a7-937f-e7b7072e04d0.jpg)

修正の仕方はどちらでも大丈夫です！

2022-12-02 12:54 UTC, caramelribon commented on src/components/templates/NewsAndEvents.scss
> +
こちらはpaddingで大丈夫です！ご確認ありがとうございます！

2022-12-03 09:15 UTC, shimamaru commented on src/components/templates/NewsAndEvents.scss
> +  padding: 60px 14% 57px;
ご回答ありがとうございます！！
横幅はcontainerのみを採用しました。
縦幅はpaddingの５６pxを採用しました。
認識が違う部分がございましたら、ご指摘いただければと思います。

2022-12-11 12:12 UTC, higashiji2000 requested changes
ほとんどいい感じです。
flexboxの機能を使ってシンプルに実装していけるとよりグッドです。

2022-12-11 12:12 UTC, higashiji2000 commented on src/components/templates/NewsAndEvents.html
> +<div class="news-events__wrap container">
![image](https://user-images.githubusercontent.com/83479175/206902207-60ef1a2a-5d3f-4f59-a7e7-d1a6fdb5add6.png)

`container`の外に背景が適用されていないので、背景用の要素でcontainerを囲む必要があります。

```suggestion
<div class="news-events__wrap">
　<div class="container">
```

2022-12-11 12:12 UTC, higashiji2000 commented on src/components/templates/NewsAndEvents.scss
> +    }
```suggestion
    @media screen and (min-width: $breakpoint-lg) {
      flex: 1;
    }
```
親がflexboxで、等しい大きさで配置したい場合はflex:1を使うのがおすすめです。
flexアイテム同士の間隔を設定する際は親に `gap` を設定すると、指定が散らばらずにすみます。

 参考：https://miyattiblog.com/explanation-of-flex-property/

2022-12-11 12:12 UTC, higashiji2000 commented on src/components/templates/NewsAndEvents.scss
> +  }
```suggestion
  @media screen and (min-width: $breakpoint-lg) {
    display: flex;
    column-gap: 40px;
  }
```
こんな感じで、`column-gap`や`row-gap`を使うことで、子要素にpaddingを設定する必要がなく、すっきりします

2022-12-11 12:12 UTC, higashiji2000 commented on src/components/templates/NewsAndEvents.scss
> +  margin: 0 auto;
中央寄せの記述は `container` に含まれているので、なくても問題ないです。

2022-12-11 12:12 UTC, higashiji2000 commented on src/components/templates/NewsAndEvents.scss
> +    }
ここは作成済みの events が間違っています。このままでもいいですし、organisms/eventsの方を直接修正しちゃっても大丈夫です。
すみません！

2022-12-13 10:14 UTC, shimamaru commented on src/components/templates/NewsAndEvents.scss
> +    }
フレックスレイアウトを使用するときに上記のようにスタイリングをした方がいいのはわかります。これからはそうしてみようと思います！
ただ今回は教えてもらったやり方で実装しようとしたところ親要素をはみ出して表示されてしまいます。
自分のコードで一応は実装できているのでこれは変更する必要があるのでしょうか？
それともフレックスレイアウトの特徴を活かしたコードに変えた方がいいのでしょうか？

これらのように実装できていたとしても、可読性の低いコードや柔軟性の低いコードは一般的に修正した方がいいのでしょうか？

<img width="905" alt="スクリーンショット 2022-12-13 18 53 52" src="https://user-images.githubusercontent.com/115210019/207287818-691edcfa-3883-43ae-9784-80ebff461ad1.png">

2022-12-14 16:18 UTC, higashiji2000 requested changes
背景の適用だけお願いします！

2022-12-14 16:18 UTC, Higashiji commented on src/components/templates/NewsAndEvents.html
> +<div class="news-events__wrap container">
こちら確認お願いします 🙏

2022-12-14 16:18 UTC, Higashiji commented on src/components/templates/NewsAndEvents.scss
> +    }
見た目に問題ないので、現状のコードでもマージして大丈夫です!

> これらのように実装できていたとしても、可読性の低いコードや柔軟性の低いコードは一般的に修正した方がいいのでしょうか？

ここに関しては、個人の学習スタイルによるのかなと思いますが、個人的には最終課題中もベストプラクティスを実践していくことをおすすめしたいです。
理由としては、案件ではチーム開発なので、可読性、拡張性のあるコードを書くことが必須になるからです。いきなりやれと言われても難しいので、練習の機会と思ってやってみるのがいいのかなと思います。
また、ベストプラクティスや問題の原因を究明する中で多くの知識を副次的にインプットすることになるのが、学習の観点からはいい感じだと思います。

問題発生 -> 調べる -> 知識がつく -> 頭の中で体系化
自分がこんな感じでやってきたのでおすすめしていますが、学習のスタイルは人それぞれです。とりあえずガンガン進めて、後から振り返るというのでも全く問題ありません！

---

今回のはみ出してしまう問題は下の記事で詳しく説明されている内容かなと思います。
https://qiita.com/mpyw/items/dfc63c1fed5dfc5eda26
試しに自分のほうでも `min-width: 0;` を設定したところ、はみ出さなくなりました。時間があればやってみてください！

2022-12-15 10:51 UTC, higashiji2000 approved these changes
LGTMです🦎

2022-12-15 10:54 UTC, merged