organisms/headerの作成(大幅変更のため新たにブランチを切って再度作成しました)
shimamaru/shimamaru-frontend-basic-last-assignment pull request #13
Opened 2022-12-03 05:15 UTC by shimamaru

## セルフチェック
- [x] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [x] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [x] 記述の重複はないか

2022-12-03 16:12 UTC, caramelribon reviewed
コメントしました！

2022-12-03 16:12 UTC, caramelribon commented on src/components/organisms/header-re/header-re.html
> +              Concept
プラスボタンがないので、つけましょう！
開閉時の＋から－の変化はつけなくても大丈夫です！

2022-12-03 16:12 UTC, caramelribon commented on src/components/organisms/header-re/header-re.html
> +  <nav class="navbar navbar-expand-lg navbar-light bg-light">
xl以上でbackgroundがグレーのヘッダーになるので、レスポンシブ対応の変更をお願いします！

2022-12-04 02:08 UTC, shimamaru commented on src/components/organisms/header-re/header-re.html
> +              Concept
`<i class="fa-regular fa-circle-plus"></i>`
というタグを使用したのですが、うまく表示されなかったため、サークルのないプラスボタンを使用しました。

2022-12-04 15:34 UTC, caramelribon commented on src/components/organisms/header-re/header-re.html
> +              Concept
ボタンはfontawesomeではなく、figmaのこの部分からexportしてください！
![スクリーンショット (1011)](https://user-images.githubusercontent.com/91133956/205499765-29b9461b-68c4-4ad0-866f-cb05e649af84.png)

2022-12-04 15:34 UTC, caramelribon reviewed
コメントしました！あと少しです！！

2022-12-06 08:25 UTC, SakaueYae commented on src/components/organisms/header-re/header-re.html
> +            >
![image](https://user-images.githubusercontent.com/101164626/205854729-cfed8883-4e8c-44ac-9688-0ed01a57c13b.png)
CONCEPTのドロップダウンがこの四角の範囲のどこをクリックしても表示されるようになっています。そのため、プラスボタンを押したときだけドロップダウンが表示され、そこ以外の範囲をクリックするとCONCEPTのリンクへ飛ぶことができるよう修正お願いします！

2022-12-06 08:25 UTC, SakaueYae commented on src/components/organisms/header-re/header-re.html
> +              </li>
![image](https://user-images.githubusercontent.com/101164626/205856172-bbfd535c-4216-4455-b168-944abda1b404.png)
CONCEPTのドロップダウン内のクリックできる範囲が少し狭めなので、横いっぱいに広げてもらうようお願いします！

2022-12-06 08:25 UTC, SakaueYae commented on src/components/organisms/header-re/header-re.scss
> +      width: 140px;
lg以下のロゴの大きさが異なるので、修正お願いします！

2022-12-06 08:25 UTC, SakaueYae commented on src/components/organisms/header-re/header-re.scss
> +              padding: 16px 0 !important;
xl以上のときは大丈夫ですが、lg以下のときの`.nav-link`の横の間隔が若干狭い気がします。

2022-12-08 04:04 UTC, shimamaru commented on src/components/organisms/header-re/header-re.html
> +            >
この部分を修正するのに、imgタグの属性にこれらを移動させたのですが、うまくいきません。
単独でwrapperクラスを外した状態ならうまく稼働したのですが、wrapperクラスを今回のようにつけたらうまくいきませんでした。

collapseの特性として自分の階層よりも上の階層のタグのトグルメニューは操作することができないというのがあるのでしょうか？

今回の実装においてヒントを頂ければ幸いです。

2022-12-08 12:41 UTC, SakaueYae commented on src/components/organisms/header-re/header-re.scss
> +              padding: 16px 0 !important;
![image](https://user-images.githubusercontent.com/101164626/206447683-a48bf7c5-4cb2-40fa-9f8e-2fca2ad7e6fe.png)
![image](https://user-images.githubusercontent.com/101164626/206448008-1f02cf42-3584-40f6-8714-8d708e4c0e87.png)
すみません、こちら逆でした...m(_ _)m
xl以上のときの横の間隔が狭い気がします！

2022-12-11 12:35 UTC, higashiji2000 commented on src/components/organisms/header-re/header-re.html
> +            >
ドキュメントの例を見ていると、
- `dropdown-toggle`
- `dropdown-menu`

という二つの要素が`dropdown`の**直下**に置いてあるので、そういう構造にしてみると治るかもしれないです。
https://getbootstrap.jp/docs/5.0/components/dropdowns/

2022-12-11 12:52 UTC, higashiji2000 requested changes
![image](https://user-images.githubusercontent.com/83479175/206904640-c7f3c1fa-c3bb-4bc6-9ad1-6484eefd91a9.png)
navbarにpaddingがついているせいでfigmaより縦に太くなっているので、修正お願いします！

2022-12-11 12:52 UTC, higashiji2000 commented on src/components/organisms/header-re/header-re.scss
> +    }
![image](https://user-images.githubusercontent.com/83479175/206903958-f508757d-05c9-4712-9d00-6bc678a88b13.png)
`dropdown` と `dropdown-menu` が離れているため、ドロップダウンをクリックしようとするとホバーが途切れてしまいます。
`.dropdown` の方高さを、ヘッダー自体の高さと同じ（100％）にすると、ドロップダウンにカーソルを移動させる途中でホバーが途切れることがなくなると思います。

2022-12-11 12:52 UTC, higashiji2000 commented on src/components/organisms/header-re/header-re.scss
> +    }
また、absoluteを使う際は基準となる要素にrelativeを設定しましょう。

2022-12-15 13:24 UTC, higashiji2000 approved these changes
LGTMです！

2022-12-15 13:24 UTC, higashiji2000 commented on src/components/organisms/header-re/header-re.html
> +              src="../../../img/Property 1=plus.svg"
エクスポートしたままだと空白が入ってる変なファイル名で保存されちゃうので、案件とかでは適切にリネームするといいかなと思います！
今回はこのままで大丈夫です。

2022-12-15 13:31 UTC, merged